blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="home"),
    path('about/', views.about, name="about"),
    path('impress/', views.impress, name="impress"),
    path('privacy/', views.privacy, name="privacy"),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('<slug:slug>', views.post_page, name="page")
    ]

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    teaser = models.CharField(max_length=255)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='test.jpeg', blank=True)
    copyright = models.CharField(max_length=75, blank=True)
    category = models.ForeignKey(
            "Category",
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
            default=None,
            related_name="posts",
        )
    def __str__(self):
        return self.title
    
    def get_related_posts(self, limit=3):
        return Post.objects.all().exclude(id=self.id).distinct()[:limit]

class Category(models.Model):
    title = models.CharField(max_length=75) 
    
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from posts.models import Post

def homepage(request):
    latest_post = Post.objects.latest('date')
    post_count = Post.objects.all().count()
    return render(request, 'home.html', {
        'latest_post': latest_post,
        'post_count': post_count
    })

def about(request):
    return render(request, 'about.html')

def impress(request):
    return render(request, 'impress.html')

def privacy(request):
    return render(request, 'privacy.html')

posts/views.py
from django.shortcuts import render
from .models import Post, Category
from django.core.paginator import Paginator


# Create your views here.
def posts_list(request, category_name=None):
    
    category_name = request.GET.get("category", category_name)
    posts = Post.objects.all().order_by('-date')

    if category_name:
        posts = posts.filter(category__title__iexact=category_name)

    categories = Category.objects.all()
    
    paginator = Paginator(posts, 10)
    page_obj = paginator.get_page(request.GET.get("page"))

    return render(request, 'posts/posts_list.html', {
        'posts': posts,
        'page_obj': page_obj,
        'categories': categories,
        'selected_category': category_name,
    })

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    related_posts = post.get_related_posts()
    return render(request, 'posts/post_page.html', {
        'post': post,
        'related_posts': related_posts
    })

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <article>
        <img 
            src="{{ post.banner.url }}"
            alt="{{post.title}}"
        />
        {% if post.copyright %}
            <p class="copyright">© {{post.copyright}}</p>
        {% endif %}
        <p class="date">{{ post.date }}</p>
        {% if post.category.title != None %}
            <div class="cat-btn">{{ post.category.title }}</div>
        {% endif %}
        <p>{{post.body | safe | linebreaks }}</p>
    </article>
    <div class="cta">
        <h2>Test</h2>
        <p>Test call!</p>
        <button>Test CTA</button>
    </div>
    <h2>You might also like:</h2>
    <div class="box">
      {% for related in related_posts %}
        <a href="{% url 'posts:page' slug=related.slug %}">
        <img class="list-img" src="{{ related.banner.url }}" alt="{{ related.title }}">
        <h3>{{ related.title }}</h3>
        </a>
      {% empty %}
        <p>Keine ähnlichen Artikel gefunden.</p>
      {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <h1>Posts</h1>
    <div class="cat-list">
        <a href="{% url 'posts:list' %}">
            <button class="cat-btn {% if not selected_category %}active{% endif %}">
                All
            </button>
        </a>
        {% for category in categories %}
            <a href="?category={{ category.title }}">
                <button class="cat-btn {% if category.title == selected_category %}active{% endif %}">
                    {{ category.title }}
                </button>
            </a>
        {% endfor %}
    </div>
    {% for post in posts %}
        <article>
            <a href="{% url 'posts:page' slug=post.slug %}">
                <img 
                    src="{{ post.banner.url }}"
                    alt="{{ post.title }}"
                />
                <h2>
                    {{ post.title }} 
                </h2>
            </a>
            {% if post.category.title != None %}
                <div class="cat-btn">{{ post.category.title }}</div>
            {% endif %}
            <p class="meta">{{ post.date }}</p>
            <p>{{ post.teaser }}</p>
        </article>
    {% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if selected_category %}&category={{ selected_category }}{% endif %}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% if selected_category %}&category={{ selected_category }}{% endif %}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>bla</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Welcome to this website. There are currently <strong>{{ post_count }}</strong> posts to discover.</p>
    <h2>My latest post:</h2>
    <article>
        <a href="{% url 'posts:page' slug=latest_post.slug %}">
            <img 
                src="{{ latest_post.banner.url }}"
                alt="{{ latest_post.title }}"
            />
            <h2>
                {{ latest_post.title }} 
            </h2>
        </a>
        <p class="date">{{ latest_post.date }}</p>
        <p>{{ latest_post.teaser }}</p>
    </article>
    <div class="cta">
        <h2>Test</h2>
        <p>Test call!</p>
        <button>Test CTA</button>
    </div>
{% endblock %}

templates/impress.html
{% extends 'layout.html' %}

{% block title %}
    Impress
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>bla</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Blog
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <div class="nav">
        <a href="{% url 'home' %}">Home</a> -
        <a href="{% url 'posts:list' %}">Posts</a> -
        <a href="{% url 'about' %}">About</a>
    </div>
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
    <div class="bottom">
        <a href="#">
            <img class="social" src="{% static 'github.svg' %}">
        </a>
        <a href="#">
            <img class="social" src="{% static 'reddit.svg' %}">
        </a>
        <a href="#">
            <img class="social" src="{% static 'linkedin.svg' %}">
        </a>
    </div>
    <div class="footer">
        <a href="{% url 'impress' %}">Impress</a> -
        <a href="{% url 'privacy' %}">Privacy</a>
    </div>
</body>
</html>

templates/privacy.html
{% extends 'layout.html' %}

{% block title %}
    Privacy
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>bla</p>
{% endblock %}